; @package    JEM
; @subpackage JEM Jubilee Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_JUBILEE="JEM - Modulo anniversari"
MOD_JEM_JUBILEE_XML_DESCRIPTION="Questo modulo mostra gli eventi anniversario come banner."
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT="Layout blocco evento"
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT_DESC="Forza facoltativamente il layout del blocco evento quando si apre un evento da questo modulo."
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT="Layout blocco sede"
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT_DESC="Forza facoltativamente il layout del blocco sede quando si apre un evento da questo modulo."
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_DETAILS="Dettagli"
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_COMPACT="Compatto"
; Module intro and footer text
MOD_JEM_JUBILEE_MODULE_TEXT_BLOCK="Introduzione e piè di pagina del modulo"
MOD_JEM_JUBILEE_SHOW_INTROTEXT="Mostra testo introduttivo"
MOD_JEM_JUBILEE_SHOW_INTROTEXT_DESC="Visualizza un testo personalizzato sopra il contenuto del modulo."
MOD_JEM_JUBILEE_INTROTEXT="Testo introduttivo"
MOD_JEM_JUBILEE_INTROTEXT_DESC="Testo visualizzato sopra il contenuto del modulo."
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT="Mostra piè di pagina"
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT_DESC="Visualizza un testo personalizzato sotto il contenuto del modulo."
MOD_JEM_JUBILEE_FOOTERTEXT="Testo piè di pagina"
MOD_JEM_JUBILEE_FOOTERTEXT_DESC="Testo visualizzato sotto il contenuto del modulo."
