; @package    JEM
; @subpackage JEM Calendar Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2008 Toni Smillie www.qivva.com
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_CAL="JEM - Modulo Calendario"
MOD_JEM_CAL_XML_DESCRIPTION="Visualizza gli eventi come un calendario mensile in una posizione del modulo.\nSu Joomla! 3.2.7+ e se il browser consente JavaScript Ajax verrà utilizzato per la ricarica minima durante la navigazione del mese."
MOD_JEM_CAL_SHOW_TOOLTIPS="Mostra suggerimenti"
MOD_JEM_CAL_SHOW_TOOLTIPS_DESC="Scegliere di visualizzare i suggerimenti con effetto rollover del mouse sulle date di calendario. "
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE="Mostra titolo dei suggerimenti"
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE_DESC="Scegli se mostrare il titolo dell'evento nel suggerimento."
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR="Titolo dei suggerimenti (Singolare)"
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR_DESC="Definisci il titolo dei suggerimenti da mostrare se il suggerimento contiene un evento. "
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL="Titolo evento nel suggerimento (plurale) "
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL_DESC="Definisci il titolo dei suggerimenti da mostrare se il suggerimento contiene più eventi."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS="Max. eventi in suggerimenti"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS_DESC="Limita il numero di eventi riportati nel suggerimento, lasciare vuoto per nessuna limitazione. "
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH="Lunghezza massima titolo evento"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH_DESC="Limita la lunghezza dei titoli degli eventi mostrati nei suggerimenti, Lasciare vuoto per nessuna limitazione."
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK="Mostra link nel suggerimento"
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK_DESC="Visualizza il link (o i link) dell'evento nei suggerimenti."
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT="Layout blocco evento"
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT_DESC="Forza facoltativamente il layout del blocco evento quando si apre un evento da questo modulo."
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT="Layout blocco sede"
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT_DESC="Forza facoltativamente il layout del blocco sede quando si apre un evento da questo modulo."
MOD_JEM_CAL_EVENT_LINK_LAYOUT_DETAILS="Dettagli"
MOD_JEM_CAL_EVENT_LINK_LAYOUT_COMPACT="Compatto"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME="Mostra orario nel suggerimento"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME_DESC="Visualizza l'orario (o gli orari) dell'evento nei suggerimenti."
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY="Mostra categoria nel suggerimento"
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY_DESC="Mostra la/le categoria/e dell'evento nei suggerimenti."
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE="Mostra sede nel suggerimento"
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE_DESC="Visualizzare la sede della manifestazione nel suggerimento "
MOD_JEM_CAL_DAYNAME_LENGTH="Lunghezza dei nomi dei giorni"
MOD_JEM_CAL_DAYNAME_LENGTH_DESC="Scegli se visualizzare il nome dei giorni per esteso oppure ridotto"
MOD_JEM_CAL_DAYNAME_DONT_DISPLAY="Non mostrare"
MOD_JEM_CAL_DAYNAME_ONE_LETTER="Singolo carattere"
MOD_JEM_CAL_DAYNAME_TWO_LETTERS="Due caratteri"
MOD_JEM_CAL_DAYNAME_THREE_LETTERS="Tre caratteri"
MOD_JEM_CAL_DAYNAME_FULL="Nome intero"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK="Inizia settimana"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK_DESC="Specifica il primo giorno della settimana."
MOD_JEM_CAL_YEAR_LENGTH="Lunghezza anno"
MOD_JEM_CAL_YEAR_LENGTH_DESC="Scegli se utilizzare 2 o 4 cifre"
MOD_JEM_CAL_TWO_DIGITS="Due cifre"
MOD_JEM_CAL_FOUR_DIGITS="Quattro cifre"
MOD_JEM_CAL_SHORT_MONTHNAME="Nome corto del mese"
MOD_JEM_CAL_SHORT_MONTHNAME_DESC="Selezionare se si desidera visualizzare i nomi abbreviati o completi del mese."
MOD_JEM_CAL_MONTH_OFFSET="Ritardo mese"
MOD_JEM_CAL_MONTH_OFFSET_DESC="Offset iniziale. Invece del mese corrente (offset 0), verranno visualizzati ad es. il prossimo mese (offset 1) o il mese precedente (offset -1)."
MOD_JEM_CAL_TIME_OFFSET="Ritardo orario (ore) "
MOD_JEM_CAL_TIME_OFFSET_DESC="Usalo SOLO se hai bisogno di compensare il tuo tempo rispetto ai settaggi del server."
MOD_JEM_CAL_REMEMBER="Ricorda"
MOD_JEM_CAL_REMEMBER_DESC="Ricorda quale mese/anno è stato selezionato alla modifica della pagina, non tornare indietro al mese corrente."
MOD_JEM_CAL_USE_AJAX="Usa AJAX"
MOD_JEM_CAL_USE_AJAX_DESC="Se impostato su Sì, la navigazione tra i mesi richiederà solo il contenuto del modulo invece di ricaricare l'intera pagina. Se JavaScript è disabilitato nel browser dell'utente, verrà comunque effettuato il ricaricamento completo della pagina."
MOD_JEM_CAL_SHOW_CURRENT_EVENTS="Mostra eventi attuali"
MOD_JEM_CAL_SHOW_CURRENT_EVENTS_DESC="Mostra eventi attuali. Non impostare 'NO' anche su mostra eventi archiviati altrimenti nessun evento sarà mostrato"
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS="Mostra eventi archiviati "
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS_DESC="Mostra eventi archiviati. Non impostare 'NO' anche su Mostra eventi correnti altrimenti non verranno visualizzati eventi."
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS="Limite alle categorie"
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS_DESC="Visualizza un calendario solo per la categoria/le categorie scelte. Lascia vuoto per nessuna limitazione."
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS="Limite alle sedi"
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS_DESC="Visualizza un calendario solo per la sede/le sedi scelte. Lascia vuoto per nessuna limitazione."
MOD_JEM_CAL_STRAIGHT_TO_DETAILS="Vai dritto ai dettagli"
MOD_JEM_CAL_STRAIGHT_TO_DETAILS_DESC="Vai direttamente alla pagina dei dettagli quando c'è un solo evento in lista."
MOD_JEM_CAL_DEFAULT_CSS="Usa CSS predefinito"
MOD_JEM_CAL_DEFAULT_CSS_DESC="Utilizzare il foglio di stile predefinito modules/mod_jem_cal/mod_jemcal.css"
MOD_JEM_CAL_USER_CSS="Usa CSS alternativo"
MOD_JEM_CAL_USER_CSS_DESC="Utilizza un foglio di stile alternativo, ad es. moduli / mod_jem_cal / mystylesheet.css. Si prega di compilare il percorso completo del file css, come nell'esempio!"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX="Suffisso classe del modulo "
MOD_JEM_CAL_MODULE_CLASS_SUFFIX_DESC="Un suffisso da applicare alla classe CSS del modulo (table.moduletable), questo permette di modificare lo stile individuale del modulo."
MOD_JEM_CAL_DEFAULT_ITEM_ID="Menù Itemid predefinito"
MOD_JEM_CAL_DEFAULT_ITEM_ID_DESC="Sostituisci l'ID oggetto utilizzato quando il collegamento del calendario va direttamente ai dettagli di una voce di menu di tua scelta."
MOD_JEM_CAL_EVENT="Evento"
MOD_JEM_CAL_EVENTS="Eventi"
MOD_JEM_CAL_CACHING="Cache"
MOD_JEM_CAL_CACHING_DESC="Selezionare se memorizzare nella cache il contenuto di questo modulo."
MOD_JEM_CAL_CACHE_TIME="Durata cache"
MOD_JEM_CAL_CACHE_TIME_DESC="Il tempo prima che il modulo venga nuovamente memorizzato nella cache."
; Module intro and footer text
MOD_JEM_CAL_MODULE_TEXT_BLOCK="Introduzione e piè di pagina del modulo"
MOD_JEM_CAL_SHOW_INTROTEXT="Mostra testo introduttivo"
MOD_JEM_CAL_SHOW_INTROTEXT_DESC="Visualizza un testo personalizzato sopra il contenuto del modulo."
MOD_JEM_CAL_INTROTEXT="Testo introduttivo"
MOD_JEM_CAL_INTROTEXT_DESC="Testo visualizzato sopra il contenuto del modulo."
MOD_JEM_CAL_SHOW_FOOTERTEXT="Mostra piè di pagina"
MOD_JEM_CAL_SHOW_FOOTERTEXT_DESC="Visualizza un testo personalizzato sotto il contenuto del modulo."
MOD_JEM_CAL_FOOTERTEXT="Testo piè di pagina"
MOD_JEM_CAL_FOOTERTEXT_DESC="Testo visualizzato sotto il contenuto del modulo."
