; @package    JEM
; @subpackage JEM Upcoming Events Basic Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_EVENTS_IN_MODULE="Eventi nel modulo"
MOD_JEM_EVENTS_IN_MODULE_DESC="Numero di eventi da mostrare nel modulo."
MOD_JEM_UPCOMING_OR_ARCHIVED="Tipo di visualizzazione degli eventi"
MOD_JEM_UPCOMING_OR_ARCHIVED_DESC="Selezionare se si desidera visualizzare i prossimi eventi, quelli non ancora passati o archiviati."
MOD_JEM_UPCOMING_EVENTS="Prossimi eventi"
MOD_JEM_UNFINISHED_EVENTS="Eventi in corso"
MOD_JEM_ARCHIVED_EVENTS="Eventi archiviati"
MOD_JEM_SHOW_NO_EVENTS="Mostra 'Nessun evento '"
MOD_JEM_SHOW_NO_EVENTS_DESC="Mostra il testo se non è stato trovato alcun evento. In caso contrario, il modulo non verrà mostrato."
MOD_JEM_HIGHLIGHT_FEATURED="Evidenzia in primo piano"
MOD_JEM_HIGHLIGHT_FEATURED_DESC="Mostra uno stile speciale per gli eventi in primo piano, per impostazione predefinita in grassetto."
MOD_JEM_OFFSET_HOURS="Tempo offset (in ore)"
MOD_JEM_OFFSET_HOURS_DESC="Sposta il tempo nel futuro (valori positivi) o nel passato (valori negativi). Utilizzato solo per visualizzare eventi non archiviati. <br>Esempi: per mostrare eventi terminati almeno due ore fa, imposta il tipo su Eventi non terminati e l'offset su -2. Per mostrare eventi che iniziano tra una settimana o più, imposta il tipo su Prossimi eventi e l'offset su 168 (7 * 24)."
MOD_JEM_DISPLAY_ORDER="Ordine di visualizzazione"
MOD_JEM_DISPLAY_ORDER_DESC="Seleziona l'ordine per titolo, data e sede."
MOD_JEM_ORDER_TDV="Titolo, Data, Sede"
MOD_JEM_ORDER_TVD="Titolo, Sede, Data"
MOD_JEM_ORDER_VTD="Sede, Titolo, Data"
MOD_JEM_ORDER_VDT="Sede, Data, Titolo"
MOD_JEM_ORDER_DTV="Data, Titolo, Sede"
MOD_JEM_ORDER_DVT="Data, Sede, Titolo"
MOD_JEM_TITLE_EVENT="Mostra titolo o sede"
MOD_JEM_TITLE_EVENT_DESC="Scegli se visualizzare il titolo dell'evento."
MOD_JEM_VENUE="Titolo sede"
MOD_JEM_TITLE="Titolo"
MOD_JEM_MAX_TITLE_LENGTH="Lunghezza massima titolo"
MOD_JEM_MAX_TITLE_LENGTH_DESC="Lunghezza massima titolo."
MOD_JEM_LINK_TO_VENUE="Link alla sede"
MOD_JEM_LINK_TO_VENUE_DESC="Link alla sede. Solo se il luogo è stato scelto prima!"
MOD_JEM_SHOW_CATEGORY="Visualizza categoria"
MOD_JEM_SHOW_CATEGORY_DESC="Mostra o nasconde la categoria dell'evento."
MOD_JEM_LINK_TO_CATEGORY="Link alla categoria"
MOD_JEM_LINK_TO_CATEGORY_DESC="Collega la categoria dell'evento quando viene mostrata."
MOD_JEM_LINK_TO_EVENT="Link all'evento attivo"
MOD_JEM_LINK_TO_EVENT_DESC="Link alla pagina dell'evento sulla data o titolo (se attivato)."
MOD_JEM_EVENT_LINK_EVENT_LAYOUT="Layout blocco evento"
MOD_JEM_EVENT_LINK_EVENT_LAYOUT_DESC="Forza facoltativamente il layout del blocco evento quando si apre un evento da questo modulo."
MOD_JEM_EVENT_LINK_VENUE_LAYOUT="Layout blocco sede"
MOD_JEM_EVENT_LINK_VENUE_LAYOUT_DESC="Forza facoltativamente il layout del blocco sede quando si apre un evento da questo modulo."
MOD_JEM_EVENT_LINK_LAYOUT_DETAILS="Dettagli"
MOD_JEM_EVENT_LINK_LAYOUT_COMPACT="Compatto"
MOD_JEM_SHOW_MORE_INFORMATION="Mostra Maggiori Informazioni"
MOD_JEM_SHOW_MORE_INFORMATION_DESC="Mostra un link o un pulsante Maggiori informazioni quando l'evento ha un articolo associato."
MOD_JEM_SHOW_MORE_INFORMATION_TITLE="Mostra titolo Maggiori Informazioni"
MOD_JEM_SHOW_MORE_INFORMATION_TITLE_DESC="Mostra il titolo dell'articolo associato dopo il testo del link Maggiori informazioni."
MOD_JEM_MORE_INFORMATION_LINK="Sì (link)"
MOD_JEM_MORE_INFORMATION_BUTTON="Sì (pulsante)"
MOD_JEM_SHOW_ICON_COUNTRY_VENUE="Mostra icona paese"
MOD_JEM_SHOW_ICON_COUNTRY_VENUE_DESC="Mostra la piccola icona del paese della sede per ogni evento."
MOD_JEM_SHOW_FLAG_ICON="Icona bandiera"
MOD_JEM_DATE="Data"
MOD_JEM_CATEGORY_ID="Categorie"
MOD_JEM_CATEGORY_ID_DESC="Scegli categorie per limitare l'output. Lasciare vuoto se si desidera visualizzare tutti gli eventi."
MOD_JEM_VENUE_ID="Sedi"
MOD_JEM_VENUE_ID_DESC="Scegli categorie per limitare l'output. Lasciare vuoto se si desidera visualizzare tutti gli eventi."
MOD_JEM_DATE_FORMAT="Formato data"
MOD_JEM_DATE_FORMAT_DESC="Formato data utilizzando il formato data di PHP, ad esempio: «j. M Y». Per maggiori informazioni <a href='https://www.php.net/manual/it/datetime.format.php' target='_blank'>consulta il manuale PHP</a>."
MOD_JEM_TIME_FORMAT="Formato ora"
MOD_JEM_TIME_FORMAT_DESC="Formato ora utilizzando il formato ora di PHP, ad esempio: «H:i». Per maggiori informazioni <a href='https://www.php.net/manual/it/datetime.format.php' target='_blank'>consulta il manuale PHP</a>."
MOD_JEM_MODULE_CLASS_SUFFIX="Suffisso classe del modulo"
MOD_JEM_MODULE_CLASS_SUFFIX_DESC="Un suffisso da applicare alla classe CSS del modulo, che ne permette lo stile indipendente."
MOD_JEM_CACHING="Cache"
MOD_JEM_CACHING_DESC="Selezionare se memorizzare nella cache il contenuto di questo modulo."
MOD_JEM_NO_CACHING="Nessuna cache"
MOD_JEM_CACHE_TIME="Durata cache"
MOD_JEM_CACHE_TIME_DESC="Il tempo prima che il modulo venga nuovamente memorizzato nella cache."
MOD_JEM="JEM - Modulo base"
MOD_JEM_XML_DESCRIPTION="JEM - Modulo base\nMostra gli eventi in un modulo "

; Frontend
MOD_JEM_NO_EVENTS="Nessun evento trovato."
MOD_JEM_MORE_INFORMATION="Maggiori informazioni"
MOD_JEM_ALL_DAY="Tutto il giorno"
; Module intro and footer text
MOD_JEM_MODULE_TEXT_BLOCK="Introduzione e piè di pagina del modulo"
MOD_JEM_SHOW_INTROTEXT="Mostra testo introduttivo"
MOD_JEM_SHOW_INTROTEXT_DESC="Visualizza un testo personalizzato sopra il contenuto del modulo."
MOD_JEM_INTROTEXT="Testo introduttivo"
MOD_JEM_INTROTEXT_DESC="Testo visualizzato sopra il contenuto del modulo."
MOD_JEM_SHOW_FOOTERTEXT="Mostra piè di pagina"
MOD_JEM_SHOW_FOOTERTEXT_DESC="Visualizza un testo personalizzato sotto il contenuto del modulo."
MOD_JEM_FOOTERTEXT="Testo piè di pagina"
MOD_JEM_FOOTERTEXT_DESC="Testo visualizzato sotto il contenuto del modulo."
