; @package    JEM
; @subpackage JEM Teaser Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_TEASER_EVENTS_IN_MODULE="Eventi nel modulo"
MOD_JEM_TEASER_EVENTS_IN_MODULE_DESC="Numero di eventi da mostrare nel modulo."
MOD_JEM_TEASER_UPCOMING_ARCHIVED_OR_CURRENT="Tipo di visualizzazione degli eventi"
MOD_JEM_TEASER_UPCOMING_ARCHIVED_OR_CURRENT_DESC="Scegliere se si desidera visualizzare gli eventi prossimi, non terminati, archiviati o attuali."
MOD_JEM_TEASER_UPCOMING_EVENTS="Prossimi"
MOD_JEM_TEASER_UNFINISHED_EVENTS="Incompleto/in corso"
MOD_JEM_TEASER_ARCHIVED_EVENTS="Archiviati"
MOD_JEM_TEASER_CURRENT_EVENTS="Oggi"
MOD_JEM_TEASER_FEATURED_EVENTS="In primo piano"
MOD_JEM_TEASER_SHOW_NO_EVENTS="Mostra 'Nessun evento '"
MOD_JEM_TEASER_SHOW_NO_EVENTS_DESC="Mostra il testo se non è stato trovato alcun evento. In caso contrario, il modulo non verrà mostrato."
MOD_JEM_TEASER_OFFSET_HOURS="Tempo offset (in ore)"
MOD_JEM_TEASER_OFFSET_HOURS_DESC="Sposta il tempo nel futuro (valori positivi) o nel passato (valori negativi). Utilizzato solo per visualizzare eventi non archiviati; per gli eventi odierni viene arrotondato ai giorni interi. <br>Esempi: per mostrare eventi terminati almeno due ore fa, imposta il tipo su Eventi non terminati e l'offset su -2. Per mostrare eventi che iniziano tra una settimana o più, imposta il tipo su Prossimi eventi e l'offset su 168 (7 * 24). Per mostrare gli eventi di domani, imposta il tipo su Oggi e l'offset su 24."
MOD_JEM_TEASER_VENUE="Sede"
MOD_JEM_TEASER_MAX_TITLE_LENGTH="Lunghezza massima titolo"
MOD_JEM_TEASER_MAX_TITLE_LENGTH_DESC="Lunghezza massima titolo."
MOD_JEM_TEASER_LINK_TO_DETAILS="Link all'evento sul titolo"
MOD_JEM_TEASER_LINK_TO_DETAILS_DESC="Link alla pagina dell'evento sul Titolo"
MOD_JEM_TEASER_EVENT_LINK_EVENT_LAYOUT="Layout blocco evento"
MOD_JEM_TEASER_EVENT_LINK_EVENT_LAYOUT_DESC="Forza facoltativamente il layout del blocco evento quando si apre un evento da questo modulo."
MOD_JEM_TEASER_EVENT_LINK_VENUE_LAYOUT="Layout blocco sede"
MOD_JEM_TEASER_EVENT_LINK_VENUE_LAYOUT_DESC="Forza facoltativamente il layout del blocco sede quando si apre un evento da questo modulo."
MOD_JEM_TEASER_EVENT_LINK_LAYOUT_DETAILS="Dettagli"
MOD_JEM_TEASER_EVENT_LINK_LAYOUT_COMPACT="Compatto"
MOD_JEM_TEASER_LINK_TO_CATEGORY="Link alla categoria"
MOD_JEM_TEASER_LINK_TO_CATEGORY_DESC="Link alla categoria."
MOD_JEM_TEASER_SHOW_CATEGORY="Visualizza categoria"
MOD_JEM_TEASER_SHOW_CATEGORY_DESC="Mostra o nasconde la categoria dell'evento."
MOD_JEM_TEASER_SHOW_VENUE="Visualizza sede"
MOD_JEM_TEASER_SHOW_VENUE_DESC="Mostra o nasconde la sede dell'evento."
MOD_JEM_TEASER_LINK_TO_VENUE="Link alla sede"
MOD_JEM_TEASER_LINK_TO_VENUE_DESC="Link alla sede."
MOD_JEM_TEASER_SHOW_DESCRIPTION_EVENT="Mostra descrizione"
MOD_JEM_TEASER_SHOW_DESCRIPTION_EVENT_DESC="Mostra la descrizione dell'evento."
MOD_JEM_TEASER_SHOW_IMAGE_EVENT="Mostra immagine evento"
MOD_JEM_TEASER_SHOW_IMAGE_EVENT_DESC="Mostra l'immagine dell'evento."
MOD_JEM_TEASER_SHOW_IMAGE_VENUE="Mostra immagine sede"
MOD_JEM_TEASER_SHOW_IMAGE_VENUE_DESC="Mostra l'immagine della sede."
MOD_JEM_TEASER_USE_MODAL="Finestra modale"
MOD_JEM_TEASER_USE_MODAL_DESC="La finestra modale mostra l'immagine in dimensioni originali dopo un clic con un piacevole effetto all'interno della schermata corrente"
MOD_JEM_TEASER_DATE="Data"
MOD_JEM_TEASER_CATEGORY_ID="Categorie"
MOD_JEM_TEASER_CATEGORY_ID_DESC="Scegli categorie per limitare l'output. Lasciare vuoto se si desidera visualizzare tutti gli eventi."
MOD_JEM_TEASER_VENUE_ID="Sedi"
MOD_JEM_TEASER_VENUE_ID_DESC="Scegli categorie per limitare l'output. Lasciare vuoto se si desidera visualizzare tutti gli eventi."
MOD_JEM_TEASER_EVENT_ID="ID evento"
MOD_JEM_TEASER_EVENT_ID_DESC="Inserisci gli ID evento separati da virgola per limitare l'output a essi. Lascia vuoto se vuoi mostrare tutti gli eventi."
MOD_JEM_TEASER_STATE="Provincia"
MOD_JEM_TEASER_STATE_DESC="Inserisci le province separate da virgola per limitare gli eventi a quelle scelte. Lascia vuoto per visualizzare gli eventi di tutte le province."
MOD_JEM_TEASER_STATE_MODE="Modalità di corrispondenza provincia"
MOD_JEM_TEASER_STATE_MODE_DESC="Seleziona se la provincia deve corrispondere esattamente a una delle stringhe indicate sopra, o semplicemente contenerne una."
MOD_JEM_TEASER_STATE_MODE_EXACTMATCH="Confronto completo"
MOD_JEM_TEASER_STATE_MODE_CONTAINS="Contiene"
MOD_JEM_TEASER_COUNTRIES="Paesi"
MOD_JEM_TEASER_COUNTRIES_DESC="Scegli i paesi per limitare l'output a essi. Lascia deselezionato se vuoi mostrare tutti gli eventi."
MOD_JEM_TEASER_SHOW_DATE="Mostra data"
MOD_JEM_TEASER_SHOW_DAY_DIFFERENCE="Mostra giorni mancanti"
MOD_JEM_TEASER_SHOW_DATE_OR_DAY_DIFFERENCE="Tipo di visualizzazione delle date"
MOD_JEM_TEASER_SHOW_DATE_OR_DAY_DIFFERENCE_DESC="Selezionare per visualizzare la data formattata o la differenza in giorni dal giorno corrente alla data dell'evento. Nota: Il tempo sarà nascosto quando è selezionata la differenza giorno."
MOD_JEM_TEASER_DATE_FORMAT="Formato data"
MOD_JEM_TEASER_DATE_FORMAT_DESC="Formato data utilizzando il formato data di PHP, ad esempio: «j. M Y». Per maggiori informazioni <a href='https://www.php.net/manual/it/datetime.format.php' target='_blank'>consulta il manuale PHP</a>."
MOD_JEM_TEASER_TIME_FORMAT="Formato ora"
MOD_JEM_TEASER_TIME_FORMAT_DESC="Formato ora utilizzando il formato ora di PHP, ad esempio: «H:i». Per maggiori informazioni <a href='https://www.php.net/manual/it/datetime.format.php' target='_blank'>consulta il manuale PHP</a>."
MOD_JEM_TEASER_MODULE_CLASS_SUFFIX="Suffisso classe del modulo"
MOD_JEM_TEASER_MODULE_CLASS_SUFFIX_DESC="Un suffisso da applicare alla classe CSS del modulo, che ne permette lo stile indipendente."
MOD_JEM_TEASER_CACHING="Cache"
MOD_JEM_TEASER_CACHING_DESC="Selezionare se memorizzare nella cache il contenuto di questo modulo."
MOD_JEM_TEASER_CACHE_TIME="Durata cache"
MOD_JEM_TEASER_CACHE_TIME_DESC="Il tempo prima che il modulo venga nuovamente memorizzato nella cache."
MOD_JEM_TEASER_ALLOW_LINEBREAK="Consenti interruzioni di riga"
MOD_JEM_TEASER_ALLOW_LINEBREAK_DESC="Consenti le interruzioni di riga o sostituiscile con uno spazio."
MOD_JEM_TEASER_COLOR="Colore"
MOD_JEM_TEASER_COLOR_DESC="Colore dell'immagine del calendario. «dalla categoria»: verrà utilizzato il colore della categoria se univoco, altrimenti il colore di riserva; «dalla sede»: verrà utilizzato il colore della sede se disponibile, altrimenti il colore di riserva."
MOD_JEM_TEASER_MAX_DESCRIPTION_LENGTH="Lunghezza massima descrizione"
MOD_JEM_TEASER_MAX_DESCRIPTION_LENGTH_DESC="Limite descrizione indicato a questa quantità di caratteri."
MOD_JEM_TEASER_BLUE="Blu"
MOD_JEM_TEASER_GREEN="Verde"
MOD_JEM_TEASER_ORANGE="Arancione"
MOD_JEM_TEASER_RED="Rosso"
MOD_JEM_TEASER_CATEGORY_COLOR="dalla categoria"
MOD_JEM_TEASER_VENUE_COLOR="dalla sede"
MOD_JEM_TEASER_FALLBACK_COLOR="Colore di riserva"
MOD_JEM_TEASER_FALLBACK_COLOR_DESC="Colore in codice HEX utilizzato per il «Colore di riserva» oppure se è selezionato «dalla categoria» ma non è disponibile un valore di colore per la categoria."
MOD_JEM_TEASER_FIELD_READMORE_DESC="Se impostato su «Sì», il link «Leggi altro…» verrà mostrato se la descrizione dell'evento contiene un'interruzione «Leggi altro»."
MOD_JEM_TEASER_FIELD_READMORE_LABEL="Mostra l'interruzione «Leggi altro…»"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION="Mostra Maggiori Informazioni"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_DESC="Mostra un link o un pulsante Maggiori informazioni quando l'evento ha un articolo associato."
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_TITLE="Mostra titolo Maggiori Informazioni"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_TITLE_DESC="Mostra il titolo dell'articolo associato dopo il testo del link Maggiori informazioni."
MOD_JEM_TEASER_READMORE_LINK="Sì (link)"
MOD_JEM_TEASER_READMORE_BUTTON="Sì (pulsante)"
MOD_JEM_TEASER_MORE_INFORMATION_LINK="Sì (link)"
MOD_JEM_TEASER_MORE_INFORMATION_BUTTON="Sì (pulsante)"

MOD_JEM_TEASER="JEM - Modulo anteprima"
MOD_JEM_TEASER_XML_DESCRIPTION="Modulo JEM Anteprima ultimi eventi"

; Frontend
MOD_JEM_TEASER_TODAY="Oggi"
MOD_JEM_TEASER_TOMORROW="Domani"
MOD_JEM_TEASER_YESTERDAY="Ieri"
MOD_JEM_TEASER_DAYS_AGO="%s giorni fa"
MOD_JEM_TEASER_DAYS_AHEAD="Tra %s giorni"
MOD_JEM_TEASER_ENDED_DAYS_AGO="Terminato %s giorni fa"
MOD_JEM_TEASER_STARTED_DAYS_AGO="Cominciato %s giorni fa"
MOD_JEM_TEASER_FROM="Dal %s"
MOD_JEM_TEASER_UNTIL="Al %s"
MOD_JEM_TEASER_FROM_UNTIL="Dal %s Al %s"
MOD_JEM_TEASER_ON_DATE="Alle %s"
MOD_JEM_TEASER_READMORE="Leggi altro..."
MOD_JEM_TEASER_MORE_INFORMATION="Maggiori informazioni"
MOD_JEM_TEASER_READMORE_REGISTER="Registrati per leggere tutto"
MOD_JEM_TEASER_NO_DESCRIPTION=""
MOD_JEM_TEASER_NO_EVENTS="Nessun evento trovato."
MOD_JEM_TEASER_ALL_DAY="Tutto il giorno"
MOD_JEM_TEASER_VENUE_COLOR_LABEL="Usa colore sede"
MOD_JEM_TEASER_VENUE_COLOR_DESC="Usa il colore della sede nell'etichetta della sede"
MOD_JEM_TEASER_CATEGORY_COLOR_LABEL="Usa colore categoria"
MOD_JEM_TEASER_CATEGORY_COLOR_DESC="Usa il colore della categoria nell'etichetta della categoria"
MOD_JEM_TEASER_COLOR_NO="No"
MOD_JEM_TEASER_COLOR_TEXT="Colore testo"
MOD_JEM_TEASER_COLOR_BG="Colore sfondo"
; Module intro and footer text
MOD_JEM_TEASER_MODULE_TEXT_BLOCK="Introduzione e piè di pagina del modulo"
MOD_JEM_TEASER_SHOW_INTROTEXT="Mostra testo introduttivo"
MOD_JEM_TEASER_SHOW_INTROTEXT_DESC="Visualizza un testo personalizzato sopra il contenuto del modulo."
MOD_JEM_TEASER_INTROTEXT="Testo introduttivo"
MOD_JEM_TEASER_INTROTEXT_DESC="Testo visualizzato sopra il contenuto del modulo."
MOD_JEM_TEASER_SHOW_FOOTERTEXT="Mostra piè di pagina"
MOD_JEM_TEASER_SHOW_FOOTERTEXT_DESC="Visualizza un testo personalizzato sotto il contenuto del modulo."
MOD_JEM_TEASER_FOOTERTEXT="Testo piè di pagina"
MOD_JEM_TEASER_FOOTERTEXT_DESC="Testo visualizzato sotto il contenuto del modulo."
