; @package    JEM
; @subpackage JEM Map Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_MAP="JEM - Modulo mappa sedi"
MOD_JEM_MAP_XML_DESCRIPTION="Visualizza su una mappa interattiva le sedi JEM che hanno latitudine e longitudine impostate in JEM."
MOD_JEM_MAP_SHOW_COUNTRY_FILTER="Mostra filtro paese"
MOD_JEM_MAP_SHOW_COUNTRY_FILTER_DESC="Visualizza un selettore di paese sopra la mappa."
MOD_JEM_MAP_COUNTRY_FILTER="Filtro paese"
MOD_JEM_MAP_ALL_COUNTRIES="Tutti i paesi"
MOD_JEM_MAP_DEFAULT_COUNTRY="Filtro paese predefinito"
MOD_JEM_MAP_DEFAULT_COUNTRY_DESC="Seleziona il paese utilizzato come filtro sede predefinito per la mappa. Lascia vuoto per mostrare le sedi di tutti i paesi."
; Module intro and footer text
MOD_JEM_MAP_MODULE_TEXT_BLOCK="Introduzione e piè di pagina del modulo"
MOD_JEM_MAP_SHOW_INTROTEXT="Mostra testo introduttivo"
MOD_JEM_MAP_SHOW_INTROTEXT_DESC="Visualizza un testo personalizzato sopra il contenuto del modulo."
MOD_JEM_MAP_INTROTEXT="Testo introduttivo"
MOD_JEM_MAP_INTROTEXT_DESC="Testo visualizzato sopra il contenuto del modulo."
MOD_JEM_MAP_SHOW_FOOTERTEXT="Mostra piè di pagina"
MOD_JEM_MAP_SHOW_FOOTERTEXT_DESC="Visualizza un testo personalizzato sotto il contenuto del modulo."
MOD_JEM_MAP_FOOTERTEXT="Testo piè di pagina"
MOD_JEM_MAP_FOOTERTEXT_DESC="Testo visualizzato sotto il contenuto del modulo."
