; JEM Types Module - sys.ini
; @package    JEM
; @subpackage JEM Types Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL

MOD_JEM_TYPES="JEM - Tipi"
MOD_JEM_TYPES_XML_DESCRIPTION="Mostra un elenco di tipi di evento con il conteggio degli eventi o i prossimi eventi principali per tipo."
MOD_JEM_TYPES_EVENT_LINK_EVENT_LAYOUT="Layout del blocco evento"
MOD_JEM_TYPES_EVENT_LINK_EVENT_LAYOUT_DESC="Forza opzionalmente il layout del blocco evento quando si apre un evento da questo modulo."
MOD_JEM_TYPES_EVENT_LINK_VENUE_LAYOUT="Layout del blocco sede"
MOD_JEM_TYPES_EVENT_LINK_VENUE_LAYOUT_DESC="Forza opzionalmente il layout del blocco sede quando si apre un evento da questo modulo."
MOD_JEM_TYPES_EVENT_LINK_LAYOUT_DETAILS="Dettagli"
MOD_JEM_TYPES_EVENT_LINK_LAYOUT_COMPACT="Compatto"
; Module intro and footer text
MOD_JEM_TYPES_MODULE_TEXT_BLOCK="Testo di introduzione e piè di pagina del modulo"
MOD_JEM_TYPES_SHOW_INTROTEXT="Mostra testo introduttivo"
MOD_JEM_TYPES_SHOW_INTROTEXT_DESC="Mostra un testo personalizzato sopra il contenuto del modulo."
MOD_JEM_TYPES_INTROTEXT="Testo introduttivo"
MOD_JEM_TYPES_INTROTEXT_DESC="Testo visualizzato sopra il contenuto del modulo."
MOD_JEM_TYPES_SHOW_FOOTERTEXT="Mostra testo piè di pagina"
MOD_JEM_TYPES_SHOW_FOOTERTEXT_DESC="Mostra un testo personalizzato sotto il contenuto del modulo."
MOD_JEM_TYPES_FOOTERTEXT="Testo piè di pagina"
MOD_JEM_TYPES_FOOTERTEXT_DESC="Testo visualizzato sotto il contenuto del modulo."
