; @package    JEM
; @subpackage JEM Banner Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_BANNER_EVENTS_IN_MODULE="Eventi nel modulo"
MOD_JEM_BANNER_EVENTS_IN_MODULE_DESC="Numero di eventi da mostrare nel modulo."
MOD_JEM_BANNER_UPCOMING_ARCHIVED_OR_CURRENT="Tipo di visualizzazione degli eventi"
MOD_JEM_BANNER_UPCOMING_ARCHIVED_OR_CURRENT_DESC="Scegliere se si desidera visualizzare gli eventi prossimi, non terminati, archiviati, attuali o solo gli eventi in evidenza."
MOD_JEM_BANNER_UPCOMING_EVENTS="Prossimi eventi"
MOD_JEM_BANNER_UNFINISHED_EVENTS="Eventi non terminati"
MOD_JEM_BANNER_ARCHIVED_EVENTS="Eventi archiviati"
MOD_JEM_BANNER_CURRENT_EVENTS="Eventi di oggi"
MOD_JEM_BANNER_OPENDATE_EVENTS="Data apertura eventi"
MOD_JEM_BANNER_SHOW_NO_EVENTS="Mostra 'Nessun evento '"
MOD_JEM_BANNER_SHOW_NO_EVENTS_DESC="Mostra il testo se non è stato trovato alcun evento. In caso contrario, il modulo non verrà mostrato."
MOD_JEM_BANNER_OFFSET_HOURS="Tempo offset (in ore)"
MOD_JEM_BANNER_OFFSET_HOURS_DESC="Sposta il tempo nel futuro (valori positivi) o nel passato (valori negativi). Utilizzato solo per visualizzare eventi non archiviati; per gli eventi odierni viene arrotondato ai giorni interi. <br>Esempi: per mostrare eventi terminati almeno due ore fa, imposta il tipo su Eventi non terminati e l'offset su -2. Per mostrare eventi che iniziano tra una settimana o più, imposta il tipo su Prossimi eventi e l'offset su 168 (7 * 24). Per mostrare gli eventi di domani, imposta il tipo su Oggi e l'offset su 24."
MOD_JEM_BANNER_VENUE="Sede"
MOD_JEM_BANNER_MAX_TITLE_LENGTH="Lunghezza massima titolo"
MOD_JEM_BANNER_MAX_TITLE_LENGTH_DESC="Lunghezza massima titolo."
MOD_JEM_BANNER_LINK_TO_DETAILS="Link all'evento sul titolo"
MOD_JEM_BANNER_LINK_TO_DETAILS_DESC="Link alla pagina dell'evento sul Titolo"
MOD_JEM_BANNER_EVENT_LINK_EVENT_LAYOUT="Layout blocco evento"
MOD_JEM_BANNER_EVENT_LINK_EVENT_LAYOUT_DESC="Forza facoltativamente il layout del blocco evento quando si apre un evento da questo modulo."
MOD_JEM_BANNER_EVENT_LINK_VENUE_LAYOUT="Layout blocco sede"
MOD_JEM_BANNER_EVENT_LINK_VENUE_LAYOUT_DESC="Forza facoltativamente il layout del blocco sede quando si apre un evento da questo modulo."
MOD_JEM_BANNER_EVENT_LINK_LAYOUT_DETAILS="Dettagli"
MOD_JEM_BANNER_EVENT_LINK_LAYOUT_COMPACT="Compatto"
MOD_JEM_BANNER_SHOWDESC="Mostra Descrizione"
MOD_JEM_BANNER_SHOWDESC_DESC="Mostra o nasconde la descrizione dell'evento."
MOD_JEM_BANNER_SHOWFLYER="Mostra Volantino"
MOD_JEM_BANNER_SHOWFLYER_DESC="Mostra o nasconde l'immagine dell'evento"
MOD_JEM_BANNER_SHOWVENUE="Visualizza sede"
MOD_JEM_BANNER_SHOWVENUE_DESC="Mostra o nascondi la sede."
MOD_JEM_BANNER_SHOWCATEGORY="Visualizza categoria"
MOD_JEM_BANNER_SHOWCATEGORY_DESC="Mostra o nasconde la categoria."
MOD_JEM_BANNER_SHOWTYPE="Mostra tipo"
MOD_JEM_BANNER_SHOWTYPE_DESC="Mostra o nasconde il tipo di evento."
MOD_JEM_BANNER_LINK_TO_CATEGORY="Link alla categoria"
MOD_JEM_BANNER_LINK_TO_CATEGORY_DESC="Link alla Categoria. Solo se Mostra Categoria è stato selezionato sopra!"
MOD_JEM_BANNER_LINK_TO_TYPE="Link al tipo"
MOD_JEM_BANNER_LINK_TO_TYPE_DESC="Link al tipo di evento. Solo se Mostra Tipo è stato selezionato sopra!"
MOD_JEM_BANNER_LINK_TO_VENUE="Link alla sede"
MOD_JEM_BANNER_LINK_TO_VENUE_DESC="Link alla Sede. Solo se Mostra sede è stato selezionato sopra!"
MOD_JEM_BANNER_FLYER_LINKS_TO="Link al Volantino"
MOD_JEM_BANNER_FLYER_LINKS_TO_DESC="Un click sull'immagine del volantino mostrerà  l'immagine in dimensioni originali su pagina intera, in una finestra popup modale, o apre la vista dei dettagli dell'evento. Questa impostazione richiede Mostra Volantino impostata su Si."
MOD_JEM_BANNER_FLYER_LINK_IMAGE_PAGE="Immagine a pagina intera"
MOD_JEM_BANNER_FLYER_LINK_IMAGE_MODAL="Immagine con finestra modale"
MOD_JEM_BANNER_FLYER_LINK_EVENT_DETAILS="Vista dettaglio dell'evento"
MOD_JEM_BANNER_DATE="Data"
MOD_JEM_BANNER_FEATURED_ONLY="Solo gli eventi in primo piano"
MOD_JEM_BANNER_FEATURED_ONLY_DESC="Limita ai soli eventi selezionati o mostra tutti gli eventi pertinenti"
MOD_JEM_BANNER_CATEGORY_ID="Categorie"
MOD_JEM_BANNER_CATEGORY_ID_DESC="Scegli categorie per limitare l'output. Lasciare vuoto se si desidera visualizzare tutti gli eventi."
MOD_JEM_BANNER_VENUE_ID="Sedi"
MOD_JEM_BANNER_VENUE_ID_DESC="Scegli categorie per limitare l'output. Lasciare vuoto se si desidera visualizzare tutti gli eventi."
MOD_JEM_BANNER_STATE="Provincia"
MOD_JEM_BANNER_STATE_DESC="Inserisci le province separate da virgola per limitare gli eventi a quelle scelte. Lascia vuoto per visualizzare gli eventi di tutte le province."
MOD_JEM_BANNER_STATE_MODE="Modalità di corrispondenza provincia"
MOD_JEM_BANNER_STATE_MODE_DESC="Seleziona se la provincia deve corrispondere esattamente a una delle stringhe indicate sopra, o semplicemente contenerne una."
MOD_JEM_BANNER_STATE_MODE_EXACTMATCH="Confronto completo"
MOD_JEM_BANNER_STATE_MODE_CONTAINS="Contiene"
MOD_JEM_BANNER_SHOW_DATE_OR_DAY_DIFFERENCE="Tipo di visualizzazione delle date"
MOD_JEM_BANNER_SHOW_DATE_OR_DAY_DIFFERENCE_DESC="Selezionare per visualizzare la data formattata o la differenza in giorni dal giorno corrente alla data dell'evento. Nota: Il tempo sarà nascosto quando è selezionata la differenza giorno."
MOD_JEM_BANNER_SHOW_DATE="Mostra data"
MOD_JEM_BANNER_SHOW_DAY_DIFFERENCE="Mostra giorni mancanti"
MOD_JEM_BANNER_DATE_FORMAT="Formato data"
MOD_JEM_BANNER_DATE_FORMAT_DESC="Formato data utilizzando il formato data di PHP, ad esempio: «j. M Y». Per maggiori informazioni <a href='https://www.php.net/manual/it/datetime.format.php' target='_blank'>consulta il manuale PHP</a>."
MOD_JEM_BANNER_TIME_FORMAT="Formato ora"
MOD_JEM_BANNER_TIME_FORMAT_DESC="Formato ora utilizzando il formato ora di PHP, ad esempio: «H:i». Per maggiori informazioni <a href='https://www.php.net/manual/it/datetime.format.php' target='_blank'>consulta il manuale PHP</a>."
MOD_JEM_BANNER_MODULE_CLASS_SUFFIX="Suffisso classe del modulo"
MOD_JEM_BANNER_MODULE_CLASS_SUFFIX_DESC="Un suffisso da applicare alla classe CSS del modulo, che ne permette lo stile indipendente."
MOD_JEM_BANNER_CACHING="Cache"
MOD_JEM_BANNER_CACHING_DESC="Selezionare se memorizzare nella cache il contenuto di questo modulo."
MOD_JEM_BANNER_CACHE_TIME="Durata cache"
MOD_JEM_BANNER_CACHE_TIME_DESC="Il tempo prima che il modulo venga nuovamente memorizzato nella cache."
MOD_JEM_BANNER_ALLOW_LINEBREAK="Consenti interruzioni di riga"
MOD_JEM_BANNER_ALLOW_LINEBREAK_DESC="Consenti le interruzioni di riga o sostituiscile con uno spazio."
MOD_JEM_BANNER_MAX_DESCRIPTION_LENGTH="Lunghezza massima descrizione"
MOD_JEM_BANNER_MAX_DESCRIPTION_LENGTH_DESC="Limite descrizione indicato a questa quantità di caratteri."
MOD_JEM_BANNER_FIELD_READMORE_DESC="Se impostato su «Sì», il link «Leggi altro…» verrà mostrato se la descrizione dell'evento contiene un'interruzione «Leggi altro»."
MOD_JEM_BANNER_FIELD_READMORE_LABEL="Mostra l'interruzione «Leggi altro…»"
MOD_JEM_BANNER_SHOW_MORE_INFORMATION="Mostra Maggiori Informazioni"
MOD_JEM_BANNER_SHOW_MORE_INFORMATION_DESC="Mostra un link o un pulsante Maggiori informazioni quando l'evento ha un articolo associato."
MOD_JEM_BANNER_SHOW_MORE_INFORMATION_TITLE="Mostra titolo Maggiori Informazioni"
MOD_JEM_BANNER_SHOW_MORE_INFORMATION_TITLE_DESC="Mostra il titolo dell'articolo associato dopo il testo del link Maggiori informazioni."
MOD_JEM_BANNER_READMORE_LINK="Sì (link)"
MOD_JEM_BANNER_READMORE_BUTTON="Sì (pulsante)"
MOD_JEM_BANNER_MORE_INFORMATION_LINK="Sì (link)"
MOD_JEM_BANNER_MORE_INFORMATION_BUTTON="Sì (pulsante)"
MOD_JEM_BANNER_EVENT_ID="ID evento"
MOD_JEM_BANNER_EVENT_ID_DESC="Inserisci gli ID evento separati da virgola per limitare l'output a essi. Lascia vuoto se vuoi mostrare tutti gli eventi."
MOD_JEM_BANNER_SHOWCALENDAR="Mostra Calendario"
MOD_JEM_BANNER_SHOWCALENDAR_DESC="Mostra un'immagine del calendario con la data dell'evento."
MOD_JEM_BANNER_COLOR="Colore"
MOD_JEM_BANNER_COLOR_DESC="Colore dell'immagine del calendario. Se è selezionato «dalla categoria», il valore del colore verrà preso dalle categorie se univoco. Altrimenti, o se è selezionato «definito dall'utente», il valore del colore verrà preso dal campo sottostante."
MOD_JEM_BANNER_BLUE="Blu"
MOD_JEM_BANNER_GREEN="Verde"
MOD_JEM_BANNER_ORANGE="Arancione"
MOD_JEM_BANNER_RED="Rosso"
MOD_JEM_BANNER_CATEGORY="dalla categoria"
MOD_JEM_BANNER_USER="definito dall'utente"
MOD_JEM_BANNER_FALLBACK_COLOR="Colore di riserva"
MOD_JEM_BANNER_FALLBACK_COLOR_DESC="Colore utilizzato se sopra è selezionato «definito dall'utente», oppure se è selezionato «dalla categoria» ma non viene trovato un valore di colore univoco."
MOD_JEM_BANNER_IMAGE_WIDTH_MAX="Larghezza massima immagine (px)"
MOD_JEM_BANNER_IMAGE_WIDTH_MAX_DESC="Valore personalizzato per la larghezza massima dell'immagine dell'evento."
MOD_JEM_BANNER_IMAGE_RATIO="Proporzioni immagine"
MOD_JEM_BANNER_IMAGE_RATIO_DESC="Seleziona le proporzioni di visualizzazione utilizzate dai layout basati su immagini. Il valore predefinito è 1:1."
MOD_JEM_BANNER_MAX_DAYS="Massimo numero di giorni"
MOD_JEM_BANNER_MAX_DAYS_DESC="Limita gli eventi prossimi o non terminati a un numero massimo di giorni, relativo all'offset orario."
MOD_JEM_BANNER_SHUFFLE="Eventi Shuffle"
MOD_JEM_BANNER_SHUFFLE_DESC="Se ci sono più eventi da mostrare, scegli casualmente gli eventi dal gruppo."
MOD_JEM_BANNER_SHUFFLE_COUNT="Limite Shuffle comuni"
MOD_JEM_BANNER_SHUFFLE_COUNT_DESC="Limiti eventi letti dal database, massima quantità, ma verrà corretto ad almeno il numero di eventi da visualizzare."
MOD_JEM_BANNER="JEM - Modulo banner"
MOD_JEM_BANNER_XML_DESCRIPTION="JEM modulo banner ultimi eventi."

; Frontend
MOD_JEM_BANNER_TODAY="Oggi"
MOD_JEM_BANNER_TOMORROW="Domani"
MOD_JEM_BANNER_YESTERDAY="Ieri"
MOD_JEM_BANNER_DAYS_AGO="%s giorni fa"
MOD_JEM_BANNER_DAYS_AHEAD="Tra %s giorni"
MOD_JEM_BANNER_DAYS_LEFT="%s giorni rimasti"
MOD_JEM_BANNER_ENDED_DAYS_AGO="Terminato %s giorni fa"
MOD_JEM_BANNER_STARTED_DAYS_AGO="Cominciato %s giorni fa"
MOD_JEM_BANNER_FROM="Dal %s"
MOD_JEM_BANNER_UNTIL="Al %s"
MOD_JEM_BANNER_FROM_UNTIL="Dal %s Al %s"
MOD_JEM_BANNER_ON_DATE="Alle %s"
MOD_JEM_BANNER_READMORE="Leggi altro..."
MOD_JEM_BANNER_MORE_INFORMATION="Maggiori informazioni"
MOD_JEM_BANNER_READMORE_REGISTER="Effettua il login per leggere maggiori dettagli."
MOD_JEM_BANNER_NO_DESCRIPTION=""
MOD_JEM_BANNER_NO_EVENTS="Nessun evento trovato."
MOD_JEM_BANNER_ALL_DAY="Tutto il giorno"
MOD_JEM_BANNER_AVAILABLE_PLACES="Posti disponibili"
MOD_JEM_BANNER_PLACES_LEFT="%s posti rimasti"
MOD_JEM_BANNER_NO_IMAGE="Nessuna immagine"
; Module intro and footer text
MOD_JEM_BANNER_MODULE_TEXT_BLOCK="Introduzione e piè di pagina del modulo"
MOD_JEM_BANNER_SHOW_INTROTEXT="Mostra testo introduttivo"
MOD_JEM_BANNER_SHOW_INTROTEXT_DESC="Visualizza un testo personalizzato sopra il contenuto del modulo."
MOD_JEM_BANNER_INTROTEXT="Testo introduttivo"
MOD_JEM_BANNER_INTROTEXT_DESC="Testo visualizzato sopra il contenuto del modulo."
MOD_JEM_BANNER_SHOW_FOOTERTEXT="Mostra piè di pagina"
MOD_JEM_BANNER_SHOW_FOOTERTEXT_DESC="Visualizza un testo personalizzato sotto il contenuto del modulo."
MOD_JEM_BANNER_FOOTERTEXT="Testo piè di pagina"
MOD_JEM_BANNER_FOOTERTEXT_DESC="Testo visualizzato sotto il contenuto del modulo."
