; @package    JEM
; @subpackage JEM Tag Plugin for AcyMailing 5.x
; @copyright  (C) 2013-2017 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note : All ini files need to be saved as UTF-8 - No BOM

PLG_TAGJEM_HELP="Aiuto"
PLG_TAGJEM_HELP_DESC="Fai clic sul pulsante di aiuto per ricevere assistenza."
PLG_TAGJEM_HIDE_PAST_EVENTS="Nascondi eventi passati"
PLG_TAGJEM_HIDE_PAST_EVENTS_DESC="Vuoi nascondere gli eventi passati?"
PLG_TAGJEM_FEATURED_EVENTS="Limita agli eventi in primo piano"
PLG_TAGJEM_FEATURED_EVENTS_DESC="Vuoi mostrare solo gli eventi in primo piano? -- Valore predefinito"
PLG_TAGJEM_SHOW_IMAGES="Mostra immagini"
PLG_TAGJEM_SHOW_IMAGES_DESC="Mostrare le immagini degli eventi? -- Valore predefinito"
PLG_TAGJEM_IMAGE_WIDTH="Larghezza massima immagine"
PLG_TAGJEM_IMAGE_WIDTH_DESC="Larghezza massima delle immagini evento, nel caso sia stato scelto sopra Mostra immagini ridimensionate -- Valore predefinito"
PLG_TAGJEM_IMAGE_HEIGHT="Altezza massima immagine"
PLG_TAGJEM_IMAGE_HEIGHT_DESC="Altezza massima delle immagini evento, nel caso sia stato scelto sopra Mostra immagini ridimensionate -- Valore predefinito"
PLG_TAGJEM_DEFAULT_ITEM_ID="Menù Itemid predefinito"
PLG_TAGJEM_DEFAULT_ITEM_ID_DESC="ID di una voce di menu che fa riferimento a una vista (elenco) JEM"
PLG_TAGJEM_OPTION_NO_SHOW_ALL="No, mostra tutti"
PLG_TAGJEM_OPTION_YES_FETURED_ONLY="Sì, solo in primo piano"
PLG_TAGJEM_OPTION_RESIZED="Ridimensionata"
PLG_TAGJEM_TITLE="Titolo"
PLG_TAGJEM_DESCRIPTION="Descrizione"
PLG_TAGJEM_DATE="Data"
PLG_TAGJEM_ID="ID"
PLG_TAGJEM_RESIZE="Ridimensiona"
PLG_TAGJEM_TEMPLATE="Modello"
PLG_TAGJEM_CONTACT="Contatto"
PLG_TAGJEM_PHONE="Telefono"
PLG_TAGJEM_CELLPHONE="Cellulare / SMS"
PLG_TAGJEM_VENUE="Sede"
