; @package    JEM
; @subpackage JEM Comments Plugin
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

PLG_JEM_COMMENTS_PLUGIN_DESC="Abilita i commenti sugli eventi con l'aiuto di JComments"
PLG_JEM_COMMENTS_COMMENTSYSTEM="Seleziona il sistema di commenti utilizzato"
PLG_JEM_COMMENTS_COMMENTSYSTEM_DESC="Seleziona il componente commenti installato."
PLG_JEM_COMMENTS_NONE="Nessuno"
PLG_JEM_COMMENTS_JCOMMENTS="JComments"
