; @package    JEM
; @subpackage JEM Action Log Plugin
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

PLG_ACTIONLOG_JEM="JEM - Registro Azioni"
PLG_ACTIONLOG_JEM_XML_DESCRIPTION="Registra le azioni selezionate degli amministratori JEM nel Registro Azioni Utente di Joomla quando abilitato nelle impostazioni di JEM."
PLG_ACTIONLOG_JEM_FIELD_LOG_EVENTS="Eventi"
PLG_ACTIONLOG_JEM_FIELD_LOG_EVENTS_DESC="Registra creazione, aggiornamento, eliminazione e cambiamenti di stato degli eventi."
PLG_ACTIONLOG_JEM_FIELD_LOG_VENUES="Sedi"
PLG_ACTIONLOG_JEM_FIELD_LOG_VENUES_DESC="Registra creazione, aggiornamento, eliminazione e cambiamenti di stato delle sedi."
PLG_ACTIONLOG_JEM_FIELD_LOG_CATEGORIES="Categorie"
PLG_ACTIONLOG_JEM_FIELD_LOG_CATEGORIES_DESC="Registra creazione, aggiornamento, eliminazione e cambiamenti di stato delle categorie."
PLG_ACTIONLOG_JEM_FIELD_LOG_TYPES="Tipi"
PLG_ACTIONLOG_JEM_FIELD_LOG_TYPES_DESC="Registra creazione, aggiornamento, eliminazione e cambiamenti di stato dei tipi."
PLG_ACTIONLOG_JEM_FIELD_LOG_GROUPS="Gruppi"
PLG_ACTIONLOG_JEM_FIELD_LOG_GROUPS_DESC="Registra creazione, aggiornamento, eliminazione e cambiamenti di stato dei gruppi JEM."
PLG_ACTIONLOG_JEM_FIELD_LOG_ATTENDEES="Partecipanti / registrazioni"
PLG_ACTIONLOG_JEM_FIELD_LOG_ATTENDEES_DESC="Registra creazione, aggiornamento, eliminazione e cambiamenti di stato delle registrazioni dei partecipanti dal backend."
PLG_ACTIONLOG_JEM_FIELD_LOG_ATTACHMENTS="Allegati"
PLG_ACTIONLOG_JEM_FIELD_LOG_ATTACHMENTS_DESC="Registra creazione, aggiornamento ed eliminazione degli allegati."
PLG_ACTIONLOG_JEM_FIELD_LOG_SETTINGS="Impostazioni"
PLG_ACTIONLOG_JEM_FIELD_LOG_SETTINGS_DESC="Registra il salvataggio delle impostazioni globali di JEM."
