; @package    JEM
; @subpackage JEM Map Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_MAP="JEM — Модуль Map"
MOD_JEM_MAP_XML_DESCRIPTION="Этот модуль показывает мероприятия на интерактивной карте."
MOD_JEM_MAP_SHOW_COUNTRY_FILTER="Показывать фильтр стран"
MOD_JEM_MAP_SHOW_COUNTRY_FILTER_DESC="Отображать выбор страны над картой."
MOD_JEM_MAP_COUNTRY_FILTER="Фильтр стран"
MOD_JEM_MAP_ALL_COUNTRIES="Все страны"
MOD_JEM_MAP_DEFAULT_COUNTRY="Фильтр стран по умолчанию"
MOD_JEM_MAP_DEFAULT_COUNTRY_DESC="Выберите страну, используемую как фильтр мест проведения по умолчанию для карты. Оставьте пустым для показа мест проведения из всех стран."
; Module intro and footer text
MOD_JEM_MAP_MODULE_TEXT_BLOCK="Вводный текст и нижний колонтитул модуля"
MOD_JEM_MAP_SHOW_INTROTEXT="Показывать вводный текст"
MOD_JEM_MAP_SHOW_INTROTEXT_DESC="Отображать пользовательский текст над содержимым модуля."
MOD_JEM_MAP_INTROTEXT="Вводный текст"
MOD_JEM_MAP_INTROTEXT_DESC="Текст, отображаемый над содержимым модуля."
MOD_JEM_MAP_SHOW_FOOTERTEXT="Показывать нижний текст"
MOD_JEM_MAP_SHOW_FOOTERTEXT_DESC="Отображать пользовательский текст под содержимым модуля."
MOD_JEM_MAP_FOOTERTEXT="Текст нижнего колонтитула"
MOD_JEM_MAP_FOOTERTEXT_DESC="Текст, отображаемый под содержимым модуля."
