; @package    JEM
; @subpackage JEM Calendar Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2008 Toni Smillie www.qivva.com
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_CAL="JEM — Модуль календаря"
MOD_JEM_CAL_XML_DESCRIPTION="Этот модуль показывает мероприятия на небольшом месячном календаре."
MOD_JEM_CAL_SHOW_TOOLTIPS="Показывать подсказки"
MOD_JEM_CAL_SHOW_TOOLTIPS_DESC="Выберите показывать ли подсказки при наведении курсора на даты календаря."
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE="Показывать заголовок подсказки"
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE_DESC="Выберите показывать ли заголовок подсказки."
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR="Заголовок подсказки (единственное число)"
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR_DESC="Определите заголовок подсказки для отображения, если подсказка содержит одно мероприятие."
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL="Заголовок подсказки (множественное число)"
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL_DESC="Определите заголовок подсказки для отображения, если подсказка содержит несколько мероприятий."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS="Макс. мероприятий в подсказке"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS_DESC="Ограничивает количество мероприятий, отображаемых в подсказке. Оставьте пустым для отсутствия ограничения."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH="Макс. длина заголовка мероприятия"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH_DESC="Ограничивает длину заголовков мероприятий в подсказках. Оставьте пустым для отсутствия ограничения."
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK="Показывать ссылку в подсказке"
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK_DESC="Отображать ссылку/ссылки мероприятия в подсказках."
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT="Макет блока мероприятия"
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT_DESC="Принудительно использовать макет блока мероприятия при открытии мероприятия из этого модуля."
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT="Макет блока места проведения"
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT_DESC="Принудительно использовать макет блока места проведения при открытии мероприятия из этого модуля."
MOD_JEM_CAL_EVENT_LINK_LAYOUT_DETAILS="Подробности"
MOD_JEM_CAL_EVENT_LINK_LAYOUT_COMPACT="Компактный"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME="Показывать время в подсказке"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME_DESC="Отображать время мероприятия в подсказках."
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY="Показывать категорию в подсказке"
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY_DESC="Отображать категорию/категории мероприятия в подсказках."
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE="Показывать место проведения в подсказке"
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE_DESC="Отображать место проведения мероприятия в подсказках."
MOD_JEM_CAL_DAYNAME_LENGTH="Длина названий дней"
MOD_JEM_CAL_DAYNAME_LENGTH_DESC="Выберите, показывать ли полное название дня или сокращённую версию."
MOD_JEM_CAL_DAYNAME_DONT_DISPLAY="Не отображать"
MOD_JEM_CAL_DAYNAME_ONE_LETTER="Один символ"
MOD_JEM_CAL_DAYNAME_TWO_LETTERS="Два символа"
MOD_JEM_CAL_DAYNAME_THREE_LETTERS="Три символа"
MOD_JEM_CAL_DAYNAME_FULL="Полное название"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK="Начало недели с"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK_DESC="Укажите первый день недели."
MOD_JEM_CAL_YEAR_LENGTH="Длина года"
MOD_JEM_CAL_YEAR_LENGTH_DESC="Выберите показывать 2 или 4 цифры."
MOD_JEM_CAL_TWO_DIGITS="Две цифры"
MOD_JEM_CAL_FOUR_DIGITS="Четыре цифры"
MOD_JEM_CAL_SHORT_MONTHNAME="Сокращённые названия месяцев"
MOD_JEM_CAL_SHORT_MONTHNAME_DESC="Выберите, отображать ли сокращённые или полные названия месяцев."
MOD_JEM_CAL_MONTH_OFFSET="Смещение месяца"
MOD_JEM_CAL_MONTH_OFFSET_DESC="Начальное смещение. Вместо текущего месяца (смещение 0), например, следующий месяц (смещение 1) или предыдущий (смещение -1)."
MOD_JEM_CAL_TIME_OFFSET="Временное смещение (часы)"
MOD_JEM_CAL_TIME_OFFSET_DESC="Используйте это ТОЛЬКО если нужно сместить время от настроек сервера."
MOD_JEM_CAL_REMEMBER="Запомнить"
MOD_JEM_CAL_REMEMBER_DESC="Запоминать выбранный месяц/год при смене страницы, не возвращаться к текущему месяцу."
MOD_JEM_CAL_USE_AJAX="Использовать AJAX"
MOD_JEM_CAL_USE_AJAX_DESC="Если «Да», навигация по месяцам будет запрашивать только содержимое модуля вместо полной перезагрузки страницы. Если JavaScript отключён, будет выполнена полная перезагрузка."
MOD_JEM_CAL_SHOW_CURRENT_EVENTS="Показывать текущие мероприятия"
MOD_JEM_CAL_SHOW_CURRENT_EVENTS_DESC="Показывать текущие мероприятия. Не устанавливайте это и «Показывать архивированные мероприятия» одновременно на «Нет», иначе мероприятия не будут отображаться."
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS="Показывать архивированные мероприятия"
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS_DESC="Показывать архивные мероприятия. Не устанавливайте это и «Показывать текущие мероприятия» одновременно на «Нет», иначе мероприятия не будут отображаться."
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS="Ограничить категориями"
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS_DESC="Отображать календарь только для выбранных категорий. Оставьте пустым для отсутствия ограничений."
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS="Ограничить местами проведения"
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS_DESC="Отображать календарь только для выбранных мест проведения. Оставьте пустым для отсутствия ограничений."
MOD_JEM_CAL_STRAIGHT_TO_DETAILS="Сразу к подробностям"
MOD_JEM_CAL_STRAIGHT_TO_DETAILS_DESC="Перейти сразу на страницу подробностей, когда есть только одно мероприятие."
MOD_JEM_CAL_DEFAULT_CSS="Использовать CSS по умолчанию"
MOD_JEM_CAL_DEFAULT_CSS_DESC="Использовать таблицу стилей по умолчанию modules/mod_jem_cal/mod_jemcal.css"
MOD_JEM_CAL_USER_CSS="Использовать альтернативный CSS"
MOD_JEM_CAL_USER_CSS_DESC="Использовать альтернативную таблицу стилей, например modules/mod_jem_cal/mystylesheet.css. Укажите полный путь к CSS-файлу!"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX="Суффикс класса модуля"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX_DESC="Суффикс, применяемый к CSS-классу модуля, что позволяет индивидуальное оформление модуля."
MOD_JEM_CAL_DEFAULT_ITEM_ID="ItemID меню по умолчанию"
MOD_JEM_CAL_DEFAULT_ITEM_ID_DESC="Переопределить ItemID, используемый при переходе по ссылке календаря, на выбранный пункт меню."
MOD_JEM_CAL_EVENT="Мероприятие"
MOD_JEM_CAL_EVENTS="Мероприятия"
MOD_JEM_CAL_CACHING="Кэширование"
MOD_JEM_CAL_CACHING_DESC="Выберите, кэшировать ли содержимое этого модуля."
MOD_JEM_CAL_CACHE_TIME="Время кэширования"
MOD_JEM_CAL_CACHE_TIME_DESC="Время до повторного кэширования модуля."
; Module intro and footer text
MOD_JEM_CAL_MODULE_TEXT_BLOCK="Вводный текст и нижний колонтитул модуля"
MOD_JEM_CAL_SHOW_INTROTEXT="Показывать вводный текст"
MOD_JEM_CAL_SHOW_INTROTEXT_DESC="Отображать пользовательский текст над содержимым модуля."
MOD_JEM_CAL_INTROTEXT="Вводный текст"
MOD_JEM_CAL_INTROTEXT_DESC="Текст, отображаемый над содержимым модуля."
MOD_JEM_CAL_SHOW_FOOTERTEXT="Показывать нижний текст"
MOD_JEM_CAL_SHOW_FOOTERTEXT_DESC="Отображать пользовательский текст под содержимым модуля."
MOD_JEM_CAL_FOOTERTEXT="Текст нижнего колонтитула"
MOD_JEM_CAL_FOOTERTEXT_DESC="Текст, отображаемый под содержимым модуля."
