; @package    JEM
; @subpackage JEM Jubilee Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_JUBILEE="JEM — Модуль Jubilee"
MOD_JEM_JUBILEE_XML_DESCRIPTION="Этот модуль показывает юбилейные мероприятия в виде баннера."
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT="Макет блока мероприятия"
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT_DESC="Принудительно использовать макет блока мероприятия при открытии мероприятия из этого модуля."
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT="Макет блока места проведения"
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT_DESC="Принудительно использовать макет блока места проведения при открытии мероприятия из этого модуля."
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_DETAILS="Подробности"
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_COMPACT="Компактный"
; Module intro and footer text
MOD_JEM_JUBILEE_MODULE_TEXT_BLOCK="Вводный текст и нижний колонтитул модуля"
MOD_JEM_JUBILEE_SHOW_INTROTEXT="Показывать вводный текст"
MOD_JEM_JUBILEE_SHOW_INTROTEXT_DESC="Отображать пользовательский текст над содержимым модуля."
MOD_JEM_JUBILEE_INTROTEXT="Вводный текст"
MOD_JEM_JUBILEE_INTROTEXT_DESC="Текст, отображаемый над содержимым модуля."
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT="Показывать нижний текст"
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT_DESC="Отображать пользовательский текст под содержимым модуля."
MOD_JEM_JUBILEE_FOOTERTEXT="Текст нижнего колонтитула"
MOD_JEM_JUBILEE_FOOTERTEXT_DESC="Текст, отображаемый под содержимым модуля."
