; @package    JEM
; @subpackage JEM Banner Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_BANNER_EVENTS_IN_MODULE="Мероприятия в модуле"
MOD_JEM_BANNER_EVENTS_IN_MODULE_DESC="Количество мероприятий, отображаемых в модуле."
MOD_JEM_BANNER_UPCOMING_ARCHIVED_OR_CURRENT="Тип отображения мероприятий"
MOD_JEM_BANNER_UPCOMING_ARCHIVED_OR_CURRENT_DESC="Выберите, показывать ли предстоящие, незавершённые, архивированные, сегодняшние или только избранные мероприятия."
MOD_JEM_BANNER_UPCOMING_EVENTS="Предстоящие мероприятия"
MOD_JEM_BANNER_UNFINISHED_EVENTS="Незавершённые мероприятия"
MOD_JEM_BANNER_ARCHIVED_EVENTS="Архивированные мероприятия"
MOD_JEM_BANNER_CURRENT_EVENTS="Сегодняшние мероприятия"
MOD_JEM_BANNER_OPENDATE_EVENTS="Мероприятия с открытой датой"
MOD_JEM_BANNER_SHOW_NO_EVENTS="Показывать «Нет мероприятий»"
MOD_JEM_BANNER_SHOW_NO_EVENTS_DESC="Показывать текст, если мероприятия не найдены. В противном случае модуль не будет отображаться."
MOD_JEM_BANNER_OFFSET_HOURS="Временное смещение (в часах)"
MOD_JEM_BANNER_OFFSET_HOURS_DESC="Сдвигает время в будущее (положительные значения) или в прошлое (отрицательные значения). Используется только для отображения неархивированных мероприятий; для сегодняшних мероприятий округляется до полных дней. <br>Примеры: Чтобы показать мероприятия, завершившиеся не менее двух часов назад, установите тип на «Незавершённые мероприятия» и смещение -2. Чтобы показать мероприятия, начинающиеся через неделю или позже, установите тип на «Предстоящие мероприятия» и смещение 168 (7 * 24). Чтобы показать мероприятия завтрашнего дня, установите тип на «Сегодня» и смещение 24."
MOD_JEM_BANNER_VENUE="Место проведения"
MOD_JEM_BANNER_MAX_TITLE_LENGTH="Макс. длина заголовка"
MOD_JEM_BANNER_MAX_TITLE_LENGTH_DESC="Максимальная длина заголовка."
MOD_JEM_BANNER_LINK_TO_DETAILS="Ссылка на мероприятие в заголовке"
MOD_JEM_BANNER_LINK_TO_DETAILS_DESC="Ссылка на страницу мероприятия в заголовке."
MOD_JEM_BANNER_EVENT_LINK_EVENT_LAYOUT="Макет блока мероприятия"
MOD_JEM_BANNER_EVENT_LINK_EVENT_LAYOUT_DESC="Принудительно использовать макет блока мероприятия при открытии мероприятия из этого модуля."
MOD_JEM_BANNER_EVENT_LINK_VENUE_LAYOUT="Макет блока места проведения"
MOD_JEM_BANNER_EVENT_LINK_VENUE_LAYOUT_DESC="Принудительно использовать макет блока места проведения при открытии мероприятия из этого модуля."
MOD_JEM_BANNER_EVENT_LINK_LAYOUT_DETAILS="Подробности"
MOD_JEM_BANNER_EVENT_LINK_LAYOUT_COMPACT="Компактный"
MOD_JEM_BANNER_SHOWDESC="Показывать описание"
MOD_JEM_BANNER_SHOWDESC_DESC="Показывать или скрывать описание мероприятия."
MOD_JEM_BANNER_SHOWFLYER="Показывать флаер"
MOD_JEM_BANNER_SHOWFLYER_DESC="Показывать или скрывать изображение мероприятия."
MOD_JEM_BANNER_SHOWVENUE="Показывать место проведения"
MOD_JEM_BANNER_SHOWVENUE_DESC="Показывать или скрывать место проведения."
MOD_JEM_BANNER_SHOWCATEGORY="Показывать категорию"
MOD_JEM_BANNER_SHOWCATEGORY_DESC="Показывать или скрывать категорию."
MOD_JEM_BANNER_SHOWTYPE="Показывать тип"
MOD_JEM_BANNER_SHOWTYPE_DESC="Показывать или скрывать тип мероприятия."
MOD_JEM_BANNER_LINK_TO_CATEGORY="Ссылка на категорию"
MOD_JEM_BANNER_LINK_TO_CATEGORY_DESC="Ссылка на категорию. Только если «Показывать категорию» выбрано выше!"
MOD_JEM_BANNER_LINK_TO_TYPE="Ссылка на тип"
MOD_JEM_BANNER_LINK_TO_TYPE_DESC="Ссылка на тип мероприятия. Только если «Показывать тип» выбрано выше!"
MOD_JEM_BANNER_LINK_TO_VENUE="Ссылка на место проведения"
MOD_JEM_BANNER_LINK_TO_VENUE_DESC="Ссылка на место проведения. Только если «Показывать место проведения» выбрано выше!"
MOD_JEM_BANNER_FLYER_LINKS_TO="Флаер ссылается на..."
MOD_JEM_BANNER_FLYER_LINKS_TO_DESC="Клик по изображению флаера покажет изображение в оригинальном размере на всю страницу, в модальном всплывающем окне или откроет страницу деталей мероприятия. Эта настройка требует, чтобы «Показывать флаер» было установлено на «Да»."
MOD_JEM_BANNER_FLYER_LINK_IMAGE_PAGE="Изображение на всю страницу"
MOD_JEM_BANNER_FLYER_LINK_IMAGE_MODAL="Изображение в модальном окне"
MOD_JEM_BANNER_FLYER_LINK_EVENT_DETAILS="Просмотр деталей мероприятия"
MOD_JEM_BANNER_DATE="Дата"
MOD_JEM_BANNER_FEATURED_ONLY="Только избранные мероприятия"
MOD_JEM_BANNER_FEATURED_ONLY_DESC="Ограничивает вывод только избранными мероприятиями или показывает все релевантные мероприятия"
MOD_JEM_BANNER_CATEGORY_ID="Категории"
MOD_JEM_BANNER_CATEGORY_ID_DESC="Выберите категории, чтобы ограничить вывод ими. Оставьте пустым, если хотите показать все мероприятия."
MOD_JEM_BANNER_VENUE_ID="Места проведения"
MOD_JEM_BANNER_VENUE_ID_DESC="Выберите места проведения, чтобы ограничить вывод ими. Оставьте пустым, если хотите показать все мероприятия."
MOD_JEM_BANNER_STATE="Округ"
MOD_JEM_BANNER_STATE_DESC="Введите разделённые запятыми округа, чтобы ограничить мероприятия выбранными. Оставьте пустым для отображения мероприятий из всех округов."
MOD_JEM_BANNER_STATE_MODE="Режим совпадения округа"
MOD_JEM_BANNER_STATE_MODE_DESC="Выберите, должен ли округ полностью совпадать с одной из строк выше или только содержать её."
MOD_JEM_BANNER_STATE_MODE_EXACTMATCH="Полное совпадение"
MOD_JEM_BANNER_STATE_MODE_CONTAINS="Содержит"
MOD_JEM_BANNER_SHOW_DATE_OR_DAY_DIFFERENCE="Тип отображения даты"
MOD_JEM_BANNER_SHOW_DATE_OR_DAY_DIFFERENCE_DESC="Выберите показывать отформатированную дату или разницу в днях от текущего дня до даты мероприятия. Примечание: время будет скрыто, если выбрана разница в днях."
MOD_JEM_BANNER_SHOW_DATE="Показывать дату"
MOD_JEM_BANNER_SHOW_DAY_DIFFERENCE="Показывать разницу в днях"
MOD_JEM_BANNER_DATE_FORMAT="Формат даты"
MOD_JEM_BANNER_DATE_FORMAT_DESC="Формат даты с использованием формата даты PHP, например: «j. M Y». Для получения дополнительной информации <a href='https://www.php.net/manual/ru/datetime.format.php' target='_blank'>посетите руководство PHP</a>."
MOD_JEM_BANNER_TIME_FORMAT="Формат времени"
MOD_JEM_BANNER_TIME_FORMAT_DESC="Формат времени с использованием формата времени PHP, например: «H:i». Для получения дополнительной информации <a href='https://www.php.net/manual/ru/datetime.format.php' target='_blank'>посетите руководство PHP</a>."
MOD_JEM_BANNER_MODULE_CLASS_SUFFIX="Суффикс класса модуля"
MOD_JEM_BANNER_MODULE_CLASS_SUFFIX_DESC="Суффикс, применяемый к CSS-классу модуля, что позволяет индивидуальное оформление модуля."
MOD_JEM_BANNER_CACHING="Кэширование"
MOD_JEM_BANNER_CACHING_DESC="Выберите, кэшировать ли содержимое этого модуля."
MOD_JEM_BANNER_CACHE_TIME="Время кэширования"
MOD_JEM_BANNER_CACHE_TIME_DESC="Время до повторного кэширования модуля."
MOD_JEM_BANNER_ALLOW_LINEBREAK="Разрешить перенос строк"
MOD_JEM_BANNER_ALLOW_LINEBREAK_DESC="Разрешить перенос строк или заменять их пробелом."
MOD_JEM_BANNER_MAX_DESCRIPTION_LENGTH="Макс. длина описания"
MOD_JEM_BANNER_MAX_DESCRIPTION_LENGTH_DESC="Ограничить отображаемое описание этим количеством символов."
MOD_JEM_BANNER_FIELD_READMORE_DESC="Если установлено «Да», ссылка «Читать далее…» будет показана, если описание мероприятия имеет разрыв «Читать далее»."
MOD_JEM_BANNER_FIELD_READMORE_LABEL="Показывать разрыв «Читать далее…»"
MOD_JEM_BANNER_SHOW_MORE_INFORMATION="Показывать «Дополнительная информация»"
MOD_JEM_BANNER_SHOW_MORE_INFORMATION_DESC="Показывать ссылку или кнопку «Дополнительная информация», когда у мероприятия есть связанная статья."
MOD_JEM_BANNER_SHOW_MORE_INFORMATION_TITLE="Показывать заголовок «Дополнительная информация»"
MOD_JEM_BANNER_SHOW_MORE_INFORMATION_TITLE_DESC="Показывать заголовок связанной статьи после текста ссылки «Дополнительная информация»."
MOD_JEM_BANNER_READMORE_LINK="Да (ссылка)"
MOD_JEM_BANNER_READMORE_BUTTON="Да (кнопка)"
MOD_JEM_BANNER_MORE_INFORMATION_LINK="Да (ссылка)"
MOD_JEM_BANNER_MORE_INFORMATION_BUTTON="Да (кнопка)"
MOD_JEM_BANNER_EVENT_ID="ID мероприятия"
MOD_JEM_BANNER_EVENT_ID_DESC="Введите разделённые запятыми ID мероприятий, чтобы ограничить вывод ими. Оставьте пустым, если хотите показать все мероприятия."
MOD_JEM_BANNER_SHOWCALENDAR="Показывать календарь"
MOD_JEM_BANNER_SHOWCALENDAR_DESC="Показывает изображение календаря с датой мероприятия."
MOD_JEM_BANNER_COLOR="Цвет"
MOD_JEM_BANNER_COLOR_DESC="Цвет изображения календаря. Если выбрано «из категории», значение цвета берётся из категорий, если оно уникально. В противном случае, или если выбрано «пользовательский», значение цвета берётся из поля ниже."
MOD_JEM_BANNER_BLUE="Синий"
MOD_JEM_BANNER_GREEN="Зелёный"
MOD_JEM_BANNER_ORANGE="Оранжевый"
MOD_JEM_BANNER_RED="Красный"
MOD_JEM_BANNER_CATEGORY="из категории"
MOD_JEM_BANNER_USER="пользовательский"
MOD_JEM_BANNER_FALLBACK_COLOR="Резервный цвет"
MOD_JEM_BANNER_FALLBACK_COLOR_DESC="Цвет, используемый, если выше выбрано «пользовательский», или «из категории», но не найдено уникальное значение цвета."
MOD_JEM_BANNER_IMAGE_WIDTH_MAX="Макс. ширина изображения (px)"
MOD_JEM_BANNER_IMAGE_WIDTH_MAX_DESC="Пользовательское значение максимальной ширины изображения мероприятия."
MOD_JEM_BANNER_IMAGE_RATIO="Соотношение сторон изображения"
MOD_JEM_BANNER_IMAGE_RATIO_DESC="Выберите соотношение сторон, используемое в макетах на основе изображений. По умолчанию 1:1."
MOD_JEM_BANNER_MAX_DAYS="Макс. дней"
MOD_JEM_BANNER_MAX_DAYS_DESC="Ограничить предстоящие или незавершённые мероприятия максимальным количеством дней относительно временного смещения."
MOD_JEM_BANNER_SHUFFLE="Случайный порядок мероприятий"
MOD_JEM_BANNER_SHUFFLE_DESC="Если мероприятий больше, чем нужно показать, случайно выбирать мероприятия из пула."
MOD_JEM_BANNER_SHUFFLE_COUNT="Лимит пула случайного выбора"
MOD_JEM_BANNER_SHUFFLE_COUNT_DESC="Ограничивает количество мероприятий, считываемых из базы данных, но будет исправлено как минимум до количества отображаемых мероприятий."
MOD_JEM_BANNER="JEM — Модуль Banner"
MOD_JEM_BANNER_XML_DESCRIPTION="Этот модуль показывает мероприятия в виде баннера."

; Frontend
MOD_JEM_BANNER_TODAY="Сегодня"
MOD_JEM_BANNER_TOMORROW="Завтра"
MOD_JEM_BANNER_YESTERDAY="Вчера"
MOD_JEM_BANNER_DAYS_AGO="%s дней назад"
MOD_JEM_BANNER_DAYS_AHEAD="через %s дней"
MOD_JEM_BANNER_DAYS_LEFT="осталось %s дней"
MOD_JEM_BANNER_ENDED_DAYS_AGO="Завершилось %s дней назад"
MOD_JEM_BANNER_STARTED_DAYS_AGO="Началось %s дней назад"
MOD_JEM_BANNER_FROM="С %s"
MOD_JEM_BANNER_UNTIL="По %s"
MOD_JEM_BANNER_FROM_UNTIL="С %s по %s"
MOD_JEM_BANNER_ON_DATE="В %s"
MOD_JEM_BANNER_READMORE="Читать далее..."
MOD_JEM_BANNER_MORE_INFORMATION="Дополнительная информация"
MOD_JEM_BANNER_READMORE_REGISTER="Войдите, чтобы прочитать подробности."
MOD_JEM_BANNER_NO_DESCRIPTION=""
MOD_JEM_BANNER_NO_EVENTS="Мероприятия не найдены."
MOD_JEM_BANNER_ALL_DAY="Весь день"
MOD_JEM_BANNER_AVAILABLE_PLACES="Доступные места"
MOD_JEM_BANNER_PLACES_LEFT="осталось %s мест"
MOD_JEM_BANNER_NO_IMAGE="Нет изображения"
; Module intro and footer text
MOD_JEM_BANNER_MODULE_TEXT_BLOCK="Вводный текст и нижний колонтитул модуля"
MOD_JEM_BANNER_SHOW_INTROTEXT="Показывать вводный текст"
MOD_JEM_BANNER_SHOW_INTROTEXT_DESC="Отображать пользовательский текст над содержимым модуля."
MOD_JEM_BANNER_INTROTEXT="Вводный текст"
MOD_JEM_BANNER_INTROTEXT_DESC="Текст, отображаемый над содержимым модуля."
MOD_JEM_BANNER_SHOW_FOOTERTEXT="Показывать нижний текст"
MOD_JEM_BANNER_SHOW_FOOTERTEXT_DESC="Отображать пользовательский текст под содержимым модуля."
MOD_JEM_BANNER_FOOTERTEXT="Текст нижнего колонтитула"
MOD_JEM_BANNER_FOOTERTEXT_DESC="Текст, отображаемый под содержимым модуля."
