; @package    JEM
; @subpackage JEM Embed Plugin
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

PLG_CONTENT_JEMEMBED="JEM — плагин Embed"
PLG_CONTENT_JEMEMBED_XML_DESCRIPTION="Плагин JEM Embed предоставляет JSON API для получения данных о событиях из расширения JEM."
PLG_CONTENT_JEMEMBED_XML_INSTRUCTION="<h3>JEM Embed</h3><p>Плагин выводит события JEM в формате JSON, который может использоваться различными способами, например, для отображения событий JEM на любых внешних сайтах (см. инструкции ниже).</p><p>Параметры вывода по умолчанию определяются в конфигурации плагина здесь. Параметры могут быть дополнены и изменены параметрами в URL вывода.</p>"
